version: "3.7"

services:
  api:
    container_name: "fastapi"
    depends_on:
      - db
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/app:cached
      - ./db:/usr/src/app/db:cached
      - ./scripts:/usr/src/app/scripts:cached
    working_dir: /usr/src/app/scripts
    command: bash -c "./run.sh"
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development
  db:
    image: fastapi_mysql
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
      - ./log/db:/var/log/mysql:cached
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development

networks:
  default:
    external:
      name: bridge
  fastapi_network:
    name: fastapi_network
    driver: bridge
    external: true
